#!/bin/bash
first=$1
second=$2
if [ -z $first -o -z $second ]
then
   echo "\
Sets exit code to 1 when the second file is not newer than the first file.  Usage:
$0 <first> <second>
Use as the 'onlyif' condition in salt states.
(Returning 0)
"
   exit 0
fi

if [ ! -e $first ]
then
   echo "$first does not exist.  Returning 0."
   exit 0
fi

if [ ! -e $second ]
then
   echo "$second does not exist. Returning 0."
   exit 0
fi

if [ $first -nt $second ]
then
   echo "$first is newer than $second.  Returning 0."
   exit 0
else
   echo "$first is not newer than $second.  Returning 1."
   exit 1
fi
